### PR TITLE
Fix link and Add installation steps for unofficial nbextensions

### PR DESCRIPTION
**Pull request by ReDeiPirati**

### CODE REVIEW

**Comment by saiprashanths** [comment]
@ReDeiPirati Step 2 in the instructions is not necessary (i.e. only need to run `jupyter-nbextension install ...` from the Jupyter terminal, not from inside the Notebook). Can you please remove this and update the PR?

**Comment by ReDeiPirati** [comment]
```
You can enable the extensions *in two ways* (we will show you how to do it for the RISE extension):

1. Terminal
2. Inside Jupyter
```
@saiprashanths  I have shown how to do it both from the Jupyter Terminal **or** Inside a Code Cell (I can replace the steps(1 and 2) with the standard list bullet if this can improve the readability). Or if you think that the 2 possibilities can confuse the reader, I'll do as you have said. 
Let me know how to proceed.

**Comment by saiprashanths** [comment]
Does doing it inside the Jupyter Notebook work? Does it require restarting the Notebook since the kernel is already active? If so, may be we can keep the instructions simple and just do: 1) Install extension on Terminal and 2) Start your Jupyter Notebook

**Comment by ReDeiPirati** [comment]
> Does doing it inside the Jupyter Notebook work? 

Yes, it works

> Does it require restarting the Notebook since the kernel is already active? 

It only needs to reload the page

> If so, may be we can keep the instructions simple and just do: 1) Install extension on Terminal and 2) Start your Jupyter Notebook

Ok, the KISS approach is always the best one, I'll go for it!

**Pull request merged**
