### PR TITLE
add guide for cyclegan

### PR DESCRIPTION
**Pull request by houqp**
Added guide and dataset for cyclegan. The guide still points to my own cyclegan fork because I can't send a PR to the upstream project without getting the datasets published on floydhub. I will do that after my data id is made public on floydhub.

Also fixed some typos in the style transfer guide.

### CODE REVIEW

**Comment by houqp** [comment]
@narenst @saiprashanths ready for review :)

**Comment by narenst** [comment]
Looks great! Thanks, @houqp. Sorry I could not get to this sooner. 

I was able to run the training step by following the instructions. Is there any way to test out the model that was generated? By passing my own image?

**Comment by narenst** [comment]
Also, I was going to fork the https://github.com/houqp/CycleGAN repo under floydhub and use that link (to have consistency in the documentation). Will that be okay?

**Comment by houqp** [comment]
> Looks great! Thanks, @houqp. Sorry I could not get to this sooner.

No worry, I know you must be busy :)

> I was able to run the training step by following the instructions. Is there any way to test out the model that was generated? By passing my own image?

Generating images should be fairly straight forward by calling `model:Forward()`. There is a `test.lua` available for adaptation. I didn't write a simple generator for that because I was waiting for the Lua serving feature so I can wrap the generation code under an API instead. If it's going to take awhile to launch the Lua serving feature, I can just document how to use test.lua with floydhub.

> Also, I was going to fork the https://github.com/houqp/CycleGAN repo under floydhub and use that link (to have consistency in the documentation). Will that be okay?

Definitely, please feel free to fork it.

**Comment by narenst** [comment]
Yeah, it would be great to have the test script - I think it will make the guide end-to-end. Do you have the script handy for that? If so please add it to the PR.

When the Lua serving feature is ready, steps to test the API can be added then.

**Comment by houqp** [comment]
Sure, I will finish up the test section on the weekend.

**Comment by houqp** [comment]
@narenst I have updated the doc and my repo.

You can see a sample test result from:
https://www.floydhub.com/viewer/data/nSUHY7VFF4rhizwdeQwN4Y/TXB5DFKvJnsE5v98Nwu95e/horse2zebra_model/latest_test/index.html

**Review by narenst — APPROVED** [review]

**Comment by narenst** [comment]
Awesome, thanks a lot @houqp!

**Pull request merged**
